name: goreleaser

on:
    pull_request:
    push:
        # run only against tags
        tags:
            - "*"

permissions:
    contents: write
    # packages: write
    # issues: write
    # id-token: write

jobs:
    release:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.22
            - uses: gerlero/brew-install@v1
              if: matrix.os == 'macos-latest'
              with:
                  packages: vips
            - name: Install Libvips for Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libvips-dev
            - name: Run GoReleaser for macOS
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: "~> v2"
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
