name: goreleaser

on:
    pull_request:
    push:
        # run only against tags
        tags:
            - "*"

permissions:
    contents: write
    # packages: write
    # issues: write
    # id-token: write

jobs:
    release-macos:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: stable
            - uses: gerlero/brew-install@v1
              with:
                  packages: vips
            - name: Run GoReleaser for macOS
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: "~> v2"
                  args: release --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    release-linux:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: stable
            - name: Install Libvips for Linux
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libvips-dev
            - name: Run GoReleaser for Linux
              uses: goreleaser/goreleaser-action@v6
              with:
                  distribution: goreleaser
                  version: "~> v2"
                  args: release -f .goreleaser-linux.yaml --clean
              env:
                  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
